### ISSUE TITLE
May be useful to autoconvert `molecule` to character

### ISSUE THREAD

**Issue by rickbeeloo** [wilkox/gggenes#20]
This may be a rare problem, however I did experience it in my case where my genome ids (thus `molecule`) are numbers. So it would be useful to mention in the documentation that the `molecule` has to be character, or convert this automatically before plotting. 

Let' s take the package example and change to numerical `molecule` ids:
```
example_genes_num <- example_genes %>% mutate(molecule = as.numeric(stringr::str_replace(molecule,'Genome','')))
ggplot(example_genes_num, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3")

```
When we then plot this (only a part shown):
![image](https://user-images.githubusercontent.com/19516376/78025603-9c044d80-735a-11ea-9f2c-a4f8598d931d.png)

This can be prevented when we convert the `molecule` to character:
```
example_genes_num <- example_genes_num %>% mutate(molecule = as.character(molecule))
ggplot(example_genes_num, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3")

```
![image](https://user-images.githubusercontent.com/19516376/78025880-0b7a3d00-735b-11ea-8923-dba2f08b36d6.png)

**Anyway, really nice and useful package!**

**Comment by wilkox** [comment]
Thanks for the suggestion @rickbeeloo! This is a ggplot2 feature, not a feature of gggenes per se – the axis ticks and labels are selected automatically depending on whether the variable is continuous or discrete (categorical). I wouldn't want to overwrite this behaviour in gggenes, since it would be inconsistent with the rest of ggplot2 and somebody might conceivably have a reason to plot molecules on a continuous y axis.
