### ISSUE TITLE
Can't change color palette when filling by continuous variable 

### ISSUE THREAD

**Issue by zreitz** [wilkox/gggenes#46]
Hello, I'm finding the extension very useful, but I have a case where I'd like to fill the genes by a continuous variable. This seems to work fine, but only with the default continuous color scale. Attempts to change the palette give no error, but no change either.

For example, these produce the same plot:
```
# R v4.1.1
# gggenes v0.4.1.9004
# ggplot2 v3.3.5

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_colour_gradient2()

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_colour_brewer(palette = "Greens")
```

In the mean time I'll just bucket the variable, but I figured I bring it to your attention in case it's an easy fix.

Thanks for your help!
-Zach

**Comment by wilkox** [comment]
Hi Zach, 

The issue here is that you are (correctly) using the `fill` aesthetic, but trying to modify it with `scale_colour_*()` functions instead of `scale_fill_*()` functions. For the first example, if you use `scale_fill_gradient2()` it should work as expected:

``` r
ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_gradient2()
```

![](https://i.imgur.com/PJoxd3O.png)

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

For the second example, if you just change `scale_colour_brewer()` to `scale_fill_brewer()`, you'll get an error because the Brewer scales (as implemented in ggplot2) are designed for discrete variables:

``` r
ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Greens")
#> Error: Continuous value supplied to discrete scale
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Instead you can use the `scale_*_distiller()` functions which will interpolate the Brewer palettes for continuous variables:

``` r
ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = start)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_distiller(palette = "Greens")
```

![](https://i.imgur.com/LHzQoSq.png)

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by zreitz** [comment]
Oh of course!  Thank you the quick reply!
