### ISSUE TITLE
Forward not working?

### ISSUE THREAD

**Issue by dplazas** [wilkox/gggenes#54]
Hi, few ays ago I installed the pckg in another pc and ran a script I had and did not work (all genes pointing same direction). After trying many different things, tested one of your examples here and it showed the same issue 

```
example_genes %>%
  mutate(direction = sample(c(-1, 1), 72, T)) %>%
  ggplot(aes(xmin = start, xmax = end, y = molecule, fill = gene, forward = direction)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes()
```
what's happening with the directions? 
thank you!

**Comment by wilkox** [comment]
Hi @dplazas, this is a bug (actually a conflict between how 'forward' was documented as working vs how it actually works) which has been fixed in the current development version. You can install the development version with `devtools::install_github('wilkox/gggenes')`. I don't have a timeline currently for when this version will be submitted to CRAN but it will get there eventually.

**Comment by dplazas** [comment]
> Hi @dplazas, this is a bug (actually a conflict between how 'forward' was documented as working vs how it actually works) which has been fixed in the current development version. You can install the development version with `devtools::install_github('wilkox/gggenes')`. I don't have a timeline currently for when this version will be submitted to CRAN but it will get there eventually.

Hi, Ok, I will keep an eye on it. Thank you very much for your help! 
Best wishes
