### ISSUE TITLE
make_alignment_dummies undefined columns selected

### ISSUE THREAD

**Issue by swuyts** [wilkox/gggenes#6]
Hi there,

Great package! Thanks!

I'm trying to create a dummy variable using 'make_alignment_dummies` as follows

```
dummies <- make_alignment_dummies(
  genes_to_plot_curated,
  aes(xmin = start, xmax = end, y = genome_split, id = Gene),
  on = "geneA"
)
``` 
This trows the following error:

```
Error in `[.data.frame`(data, as.character(unlist(mapping))) : 
  undefined columns selected
```

geneA is definitely present in column Gene as I use almost the exact same aes call in the plot version (replacing 'id' with 'fill'). Would you be able to give me some insights in what's happening here?

Sorry about not providing a reproducible example.

Thanks!

**Comment by wilkox** [comment]
Thanks for the bug report. Are you using the development version of ggplot2 (2.2.1.9000) by any chance? You can check by running `sessionInfo()`.

**Comment by swuyts** [comment]
Yes, you are correct! 

I now suspect that's a problem?

**Comment by wilkox** [comment]
Glad to hear you found a fix! The problem was due to [some backwards-incompatible changes being introduced in the next version of ggplot2](https://www.tidyverse.org/articles/2018/05/ggplot2-2-3-0/).

I've already updated the development version of gggenes to support these changes, so if you want to keep using the development version of ggplot2 you can just install gggenes from GitHub: `devtools::install_github('wilkox/gggenes')`. I'll be submitting the new version to CRAN soon.
